# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyIOSAPP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GCJSONKit', '~> 1.5.0'
  # Pods for MyIOSAPP
  pod 'Masonry', '~> 1.1.0'
  pod 'pop', '~> 1.0'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'ReactiveCocoa', '~> 2.5'
  target 'MyIOSAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyIOSAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
